### ISSUE TITLE
account.upgrade error 

### ISSUE THREAD

**Issue by aballester92** [nylas/nylas-nodejs#181]
i was testing the account.downgrade / upgrade for a prospect and ran into an issue when using the node sdk and successfully downgraded but got an error with the update function.  up/downgrading with postman works fine. 

**CODE:** 
`const Nylas = require('nylas')

Nylas.config({
        clientId: 'REDACTED',
        clientSecret: 'REDACTED',
    })

    
    Nylas.accounts.find('REDACTED').then(account => account.uprade())
    .then(response => console.log(response));`

**ERROR:**
```
alexballester@Alexs-MacBook-Pro q1-project % node reauthTest.js
(node:39381) UnhandledPromiseRejectionWarning: TypeError: account.uprade is not a function at /Users/alexballester/q1-project/reauthTest.js:10:74
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:39381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
alexballester@Alexs-MacBook-Pro q1-project % 
```

**Comment by Gerdie** [comment]
Hi @aballester92 you have a typo in `upgrade`.
