### ISSUE TITLE
6.2.0 breaks `source-map-support`

### ISSUE THREAD

**Issue by KazimirPodolski** [nylas/nylas-nodejs#323]
**Describe the bug**
Latest version (6.2.0) breaks source maps provided by `source-map-support` through `ts-node-dev`:
```
TypeError: Cannot read property 'String' of undefined
    at /usr/src/project/node_modules/nylas/lib/models/restful-model.js:130:34
    at Object.<anonymous> (/usr/src/project/node_modules/nylas/lib/models/restful-model.js:145:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/usr/src/project/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.nodeDevHook [as .js] (/usr/src/project/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

**To Reproduce**
Start something which uses sdk with `ts-node-dev`:
```
ts-node-dev server.ts
```
Not sure how to provide complete reproducible test case for now. Tried with the latest versions too:
```
{
    "devDependencies": {
        "ts-node-dev": "^1.1.8",
	"source-map-support": "^0.5.21"
    }
}
```

**Expected behavior**
Loading does not fail.

**SDK Version:**
6.2.0

**Additional context**
6.0.0 is fine. I understand it's not nylas sdk's issue, but `source-map-support` looks abandoned, so maybe there is something could be done on sdk's part?

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thank you for opening this issue! I tried to reproduce this issue but with `source-map-support` and `ts-node-dev` but I am unable to get the same error you are getting on v6.2.0. Is there any code snippet you can provide from your end so I can reproduce it and debug from there? Thanks!

**Comment by KazimirPodolski** [comment]
@mrashed-dev Turns out I'm suffering from this one https://github.com/wclr/ts-node-dev/issues/185.

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thanks for sharing that and closing the issue!
