### ISSUE TITLE
Expose file download() errors

### ISSUE THREAD

**Issue by wheeler** [nylas/nylas-nodejs#34]
Descriptive errors are not thrown by the file `download` method.

  Example of good error reporting (file.metadata()):

```
nylasapi.files.build({id: 'bogusid'}).metadata();

Error: Couldn't find file bogusid 
    at NylasConnection.module.exports.NylasConnection.request (.../npm/node_modules/nylas/lib/nylas-connection.js:104:14)
    at NylasConnection.Nylas.NylasConnection.request (meteor://app/server/lib/nylas.js:206:25)
    at File.module.exports.File.metadata (.../npm/node_modules/nylas/lib/models/file.js:131:30)
```

Poor error reporting (file.download()):

```
nylasapi.files.build({id: 'bogusid'}).download();

Error
    at NylasConnection.module.exports.NylasConnection.request (.../npm/node_modules/nylas/lib/nylas-connection.js:104:14)
    at NylasConnection.Nylas.NylasConnection.request (meteor://app/server/lib/nylas.js:206:25)
    at File.module.exports.File.download (.../npm/node_modules/nylas/lib/models/file.js:101:30)
    at File.download (.../npm/node_modules/nylas/lib/models/file.js:3:59)
```

**Comment by qbalin** [comment]
+1

**Comment by mccolin** [comment]
Similar to the message send / SMTP issue -- file downloads have been a blackbox for us because of this issue.

**Comment by jackiehluo** [comment]
Closing this issue for now because it looks like we now return the same error for both (`Error: Couldn't find file 123`)—if that's not the case and you can still reproduce, let me know, and we'll look into it!
