### ISSUE TITLE
No recipients specified error when using the sdk

### ISSUE THREAD

**Issue by freitasjuciel** [nylas/nylas-nodejs#426]
**Describe the bug**
When I try to send an email using the Draft class it returns and `No recipients specified` error. But when sending the request with the same fields it works properly

**To Reproduce**
Some steps involved to reproduce the bug and any code samples you can share.
```
Nylas.config({
    clientId: process.env.NYLAS_CLIENT_ID,
    clientSecret: process.env.NYLAS_CLIENT_SECRET,
  });

  const nylas = Nylas.with(decrypt(user.nylasToken, user.nylasTokenIv));
  
  const draft = new NylasDraft(nylas, {
    subject: emailMessage.subject,
    body: htmlBody.toString(),
    from: [{ name: `${user.firstName} ${user.lastName}`.trim(), email: user.email }],
    to: [{ email: emailThread.email }],
  });
  
  const result = await draft.send((error, data) => {
    console.log(error);
    console.log(data);
  });
```

**Expected behavior**
Send the email since the from and to emails are in the body

**SDK Version:**
6.6.9, 6.7.0, 6.8.0

**Additional context**
When using the request method from nylas it works properly
```
await nylas.request({
    path: "/send",
    method: "POST",
    json: true,
    body: {
      subject: emailMessage.subject,
      body: htmlBody.toString(),
      from: [{ name: `${user.firstName} ${user.lastName}`.trim(), email: user.email }],
      to: [{ email: emailThread.email }],
      files: files,
    },
  });
```

![image](https://user-images.githubusercontent.com/7970477/222925335-d238a1b4-833b-4f8c-8da7-9800e69205c6.png)

**Comment by Dm-Chebotarskyi** [comment]
I can see the same issue by executing this code:
```typescript
    const { to, subject, body, reply_to_message_id, email_address } =
      event.body;

    console.log('>>> to', to);

    const draft = new Draft(nylas, {
      from: [{ email: email_address }],
      to: [{ email: to }],
      subject: subject,
      body: body,
      replyToMessageId: reply_to_message_id,
    });
```

And here is the console output:
```
>>> to you@gmail.com

Bad Request: No recipients specified
    at null.e (/Users/dimach/workspace/app-api/node_modules/nylas/lib/models/nylas-api-error.js:31:28)
    at null.<anonymous> (/Users/dimach/workspace/app-api/node_modules/nylas/lib/nylas-connection.js:215:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorMapping: {
    '400': 'Bad Request',
    '401': 'Unauthorized',
    '402': 'Request Failed or Payment Required',
    '403': 'Forbidden',
    '404': 'Not Found',
    '405': 'Method Not Allowed',
    '409': 'Conflict',
    '410': 'Gone',
    '418': "I'm a Teapot",
    '422': 'Sending Error',
    '429': 'Too Many Requests',
    '500': 'Server Error',
    '502': 'Server Error',
    '503': 'Server Error',
    '504': 'Server Error'
  },
  statusCode: 400,
  type: 'invalid_request_error'
}
{"level":"info","message":{"response":{"body":"No recipients specified","headers":{"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Origin":"https://dev.exacare.com","Content-Type":"text/plain","Vary":"Origin"},"statusCode":400}}}
```

**Comment by djakaitis** [comment]
We are still experiencing this exact issue when using the SDK to create a Draft and send. Is there any resolution here or workaround to still use a Draft object?

**Comment by Dm-Chebotarskyi** [comment]
> We are still experiencing this exact issue when using the SDK to create a Draft and send. Is there any resolution here or workaround to still use a Draft object?

I used a `nylas.request` as described in the original question to workaround it

**Comment by relaxedtomato** [comment]
Hi @djakaitis - is this your latest code snippet:

```js
Nylas.config({
    clientId: process.env.NYLAS_CLIENT_ID,
    clientSecret: process.env.NYLAS_CLIENT_SECRET,
  });

  const nylas = Nylas.with(decrypt(user.nylasToken, user.nylasTokenIv));
  
  const draft = new NylasDraft(nylas, {
    subject: emailMessage.subject,
    body: htmlBody.toString(),
    from: [{ name: `${user.firstName} ${user.lastName}`.trim(), email: user.email }],
    to: [{ email: emailThread.email }],
  });
  
  const result = await draft.send((error, data) => {
    console.log(error);
    console.log(data);
  });
  ```
  
  I just tested the following on my machine and it works:
```js
  // Import your dependencies
import dotenv from "dotenv/config.js";
import Nylas from "nylas";
import Draft from "nylas/lib/models/draft.js";

// Configure your Nylas client
Nylas.config({
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
});
const nylas = Nylas.with(process.env.ACCESS_TOKEN);

// Create a draft email
const draft = new Draft.default(nylas, {
  subject: "With Love, from Nylas",
  body: "Well well well...",
  to: [{ name: "Recipient name", email: process.env.RECIPIENT_ADDRESS }],
});

// Send the email
try {
  const message = await draft.send();
  console.log(`Message "${message.subject}" was sent with ID ${message.id}`);
} catch (err) {
  console.error("Error:\n", err);
}

```
  
  I receive the following message in the console:
  ```
  Message "With Love, from Nylas" was sent with ID 28ou45lvggumtfdfqap2ti84g
  ```
  
Here are a few steps to try to see if it helps:
- Take the above working code sample and try it out by replacing the `process.env` values in a separate file
- Try adding a few console logs to ensure the correct values are being added

**Comment by mrashed-dev** [comment]
Hey @djakaitis were you able to resolve the issue with @relaxedtomato's comment or are you still seeing the same issue?

**Comment by mrashed-dev** [comment]
Closing this issue, @djakaitis let us know if you still need help.
