### ISSUE TITLE
missing static method when using "import" in typescript

### ISSUE THREAD

**Issue by ianzone** [nylas/nylas-nodejs#457]
**Describe the bug**
Nylas.config() is undefined, when using `import Nylas from 'nylas'`
```
Nylas.config({ clientId: '', clientSecret: '' });
      ^
TypeError: Cannot read properties of undefined (reading 'config')
    at Object.<anonymous> (/home/ian/acte/roomzz-v1/api/booking/test.ts:3:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/ian/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.4/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ian/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.4/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/ian/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.4/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/home/ian/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.4/node_modules/ts-node/src/bin.ts:95:10)
```

**To Reproduce**
in test.ts
```
import Nylas from 'nylas';

Nylas.config({ clientId: '', clientSecret: '' });
```
then run `ts-node test.ts`

**SDK Version:**
6.10.0

**Comment by relaxedtomato** [comment]
Hi @ianzone, does the following syntax work?

`const Nylas = require('nylas');`

**Comment by relaxedtomato** [comment]
Just to clarify, we support [CommonJS modules](https://nodejs.org/api/modules.html#modules-commonjs-modules)

**Comment by ianzone** [comment]
> Hi @ianzone, does the following syntax work?
> 
> `const Nylas = require('nylas');`

It does, but ESM is pretty much the standard for js libraries nowadays.

**Comment by mrashed-dev** [comment]
Thanks @ianzone for submitting this issue, the feature is complete and will be included in the next major release of the SDK. We will have the first beta coming out very soon!
