### ISSUE TITLE
TypeError: Cannot create property 'statusCode' on string 'Daily sending quota exceeded

### ISSUE THREAD

**Issue by TalhaAwan** [nylas/nylas-nodejs#86]
```
/home/talha/Desktop/nylas-test/node_modules/nylas/lib/nylas-connection.js:223
              error.statusCode = response.statusCode;
                               ^

TypeError: Cannot create property 'statusCode' on string 'Daily sending quota exceeded (Server Error: 550 : 5.4.5 Daily user sending quota exceeded. h79sm13695820pfj.186 - gsmtp)'
    at Request._callback (/home/talha/Desktop/nylas-test/node_modules/nylas/lib/nylas-connection.js:223:32)
    at Request.self.callback (/home/talha/Desktop/nylas-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/talha/Desktop/nylas-test/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/talha/Desktop/nylas-test/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I was testing the library for quota exceeded error. The error does appear, but crashes the server/script because how it's handled in `nylas-connection.js`:

```
if (error || response.statusCode > 299) {
  if (!error) {
    error = new Error(body.message);
  }
  if (body.server_error) {
    error = error.message + ' (Server Error: ' + body.server_error + ')';
  }
  if (response.statusCode) {
    error.statusCode = response.statusCode; // here
  }
  return reject(error);
} else {
  if (options.downloadRequest) {
    return resolve(response);
  } else {
    return resolve(body);
  }
}
```

I can send a PR, if I know the status of the project. It was last published 10 months ago, which shows it's not actively maintained.

**Comment by Gerdie** [comment]
Hi @TalhaAwan this should be fixed in version 4.6.1, please re-open if you are still seeing errors after upgrading.
